# SPDX-FileCopyrightText: 2022 Contributors to the Power Grid Model project <dynamic.grid.calculation@alliander.com>
#
# SPDX-License-Identifier: MPL-2.0

[project]
requires-python = ">=3.8"

[build-system]
requires = [
    "setuptools",
    "wheel",
    "cython",
    "numpy",
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
# Switch to using build
build-frontend = "build"
test-requires = ["pytest", "pytest-cov"]
test-command = "pytest"

[tool.cibuildwheel.macos]
archs = ["x86_64", "universal2", "arm64"]

[tool.pytest.ini_options]
testpaths = ["tests/unit"]
addopts = ["--cov", "--cov-report", "term", "--cov-report", "html:python_cov_html", "--cov-report", "xml:python_coverage.xml"]

[tool.coverage.run]
source = ["power_grid_model"]

[tool.coverage.report]
fail_under = 95

[tool.black]
line-length = 120
target-version = ['py38']
