# SPDX-FileCopyrightText: 2022 Contributors to the Power Grid Model project <dynamic.grid.calculation@alliander.com>
#
# SPDX-License-Identifier: MPL-2.0

[project]
requires-python = ">=3.8"


[build-system]
requires = [
    "setuptools",
    "wheel",
    "cython",
    "oldest-supported-numpy",
]
build-backend = "setuptools.build_meta"


[tool.cibuildwheel]
# build-frontend = "build"
build-verbosity = 1

# Skip trying to test arm64 builds on Intel Macs
test-skip = "*-macosx_arm64 *-macosx_universal2:arm64"

test-requires = ["pytest", "pytest-cov"]
test-command = "pytest {package}/tests"


[tool.cibuildwheel.macos]
archs = ["universal2"]


[tool.cibuildwheel.linux]
archs = ["x86_64"]


[tool.cibuildwheel.windows]
archs = ["AMD64"]


[tool.pytest.ini_options]
testpaths = ["tests/unit"]
addopts = ["--cov=power_grid_model", "--cov-report", "term", "--cov-report", "html:python_cov_html", "--cov-report", "xml:python_coverage.xml", "--cov-fail-under=95"]


[tool.black]
line-length = 120
target-version = ['py38']
