# SPDX-FileCopyrightText: 2022 Contributors to the Power Grid Model project <dynamic.grid.calculation@alliander.com>
#
# SPDX-License-Identifier: MPL-2.0

name: Sonar Cloud

on:
  # run pipeline on push event of main or release branch
  push:
    branches:
      - main
      - 'release/**'
  # run pipeline on pull request
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PYTHON_VERSION: cp310-cp31

jobs:
  sonar-cloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    container: ghcr.io/alliander-opensource/power-grid-model-build-env:latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Test
        run: |
          /opt/python/${PYTHON_VERSION}/bin/pip install --no-build-isolation -v --no-deps -e .
          /opt/python/${PYTHON_VERSION}/bin/pytest
          cat python_coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
